-- 코드를 입력하세요
SELECT AUT.AUTHOR_ID, AUT.AUTHOR_NAME, BO.CATEGORY, SUM(SAL.SALES * BO.PRICE) AS SALES
FROM BOOK BO
JOIN AUTHOR AUT
ON BO.AUTHOR_ID = AUT.AUTHOR_ID
JOIN BOOK_SALES SAL
ON BO.BOOK_ID = SAL.BOOK_ID
WHERE YEAR(SAL.SALES_DATE) = 2022 AND MONTH(SAL.SALES_DATE) = 1
GROUP BY AUT.AUTHOR_ID, BO.CATEGORY
ORDER BY AUT.AUTHOR_ID ASC, BO.CATEGORY DESC