-- 코드를 입력하세요
WITH IN_REMOVE_SEX AS(
    SELECT A_IN.ANIMAL_ID
    FROM ANIMAL_INS A_IN
    JOIN ANIMAL_OUTS A_OUT
    ON A_IN.ANIMAL_ID = A_OUT.ANIMAL_ID
    WHERE A_IN.SEX_UPON_INTAKE LIKE 'Intact%' AND NOT(A_OUT.SEX_UPON_OUTCOME LIKE 'Intact%')
)

SELECT R_IN.ANIMAL_ID, R_IN.ANIMAL_TYPE, R_IN.NAME
FROM ANIMAL_INS R_IN
JOIN IN_REMOVE_SEX RS
ON R_IN.ANIMAL_ID = RS.ANIMAL_ID
ORDER BY R_IN.ANIMAL_ID