-- 코드를 입력하세요
SELECT INFOS.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS,
ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO INFOS
JOIN REST_REVIEW REVIEWS
    ON INFOS.REST_ID = REVIEWS.REST_ID
WHERE INFOS.ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, INFOS.FAVORITES DESC