-- 코드를 입력하세요
WITH TOTAL AS(
    SELECT ORD.PRODUCT_ID, SUM(ORD.AMOUNT) AS TOTAL_SALES
    FROM FOOD_ORDER ORD
    WHERE YEAR(ORD.PRODUCE_DATE) = 2022 and MONTH(ORD.PRODUCE_DATE) = 5
    GROUP BY ORD.PRODUCT_ID
)

SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, PRO.PRICE * TOT.TOTAL_SALES AS TOTAL_SALES
    FROM FOOD_PRODUCT PRO
    JOIN TOTAL TOT
    ON PRO.PRODUCT_ID = TOT.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID ASC