-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
date_format(DATE_OF_BIRTH, "%Y-%m-%d")
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 and not TLNO = 'NULL' and GENDER = 'W'
ORDER BY MEMBER_ID ASC