-- 코드를 입력하세요
WITH SUMSALE AS(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
)

SELECT US.USER_ID, US.NICKNAME, SS.TOTAL_SALES
FROM USED_GOODS_USER US
JOIN SUMSALE SS
ON US.USER_ID = SS.WRITER_ID
WHERE SS.TOTAL_SALES >= 700000
ORDER BY SS.TOTAL_SALES ASC