-- 코드를 입력하세요
WITH NUMOFREN AS
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' and START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT MONTH(HIS.START_DATE) AS MONTH, HIS.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
WHERE HIS.CAR_ID IN (
    SELECT NR.CAR_ID FROM NUMOFREN NR
) AND HIS.START_DATE >= '2022-08-01' and HIS.START_DATE < '2022-11-01'
GROUP BY HIS.CAR_ID, MONTH(HIS.START_DATE)
ORDER BY MONTH ASC, HIS.CAR_ID DESC