-- 코드를 작성해주세요

SELECT F_I2.ID,F_NI.FISH_NAME, F_I2.LENGTH
FROM FISH_INFO F_I2
JOIN FISH_NAME_INFO F_NI
ON F_I2.FISH_TYPE = F_NI.FISH_TYPE
WHERE (F_I2.FISH_TYPE, F_I2.LENGTH) IN (SELECT F_I.FISH_TYPE, MAX(F_I.LENGTH)
FROM FISH_INFO F_I
GROUP BY F_I.FISH_TYPE)
ORDER BY F_I2.ID ASC