WITH FI AS
(
    SELECT F1.CATEGORY, MAX(F1.PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT F1
        WHERE F1.CATEGORY IN ('과자', '국', '김치', '식용유')
        GROUP BY F1.CATEGORY
)

-- 코드를 입력하세요
SELECT F2.CATEGORY, F2.PRICE AS MAX_PRICE, F2.PRODUCT_NAME
FROM FOOD_PRODUCT F2
JOIN FI F
ON F2.CATEGORY = F.CATEGORY
WHERE F2.PRICE = F.MAX_PRICE
ORDER BY MAX_PRICE DESC;